version: 2.1

jobs:
  Deploy:
    docker:
       - image: cimg/node:14.17.0
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          command: |
            yarn install
      - save_cache:
          key: v1-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
            - yar
      - run:
          name: Creating new Build
          command: |
            CI=false yarn run build-demo
      - run:
          name: Run Linting
          command: |
            yarn lint
      - run:
          name: Run Tests
          command: |
            yarn test
